---
- name: Using our new module
  hosts: localhost

  tasks:
  - name: New module
    my_new_test_module:
      name: Chester
      color: blue
      augment: true
    register: results

  - debug:
      var: results
